ClusterName=kfi-hpc
SlurmctldHost=hpc-controller

AuthType=auth/munge
CryptoType=crypto/munge

SlurmUser=slurm
SlurmdUser=root

StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd

SwitchType=switch/none
MpiDefault=none

ProctrackType=proctrack/linuxproc
ReturnToService=2

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core

SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid

NodeName=hpc-compute01 CPUs=2 Boards=1 SocketsPerBoard=1 CoresPerSocket=1 ThreadsPerCore=2 RealMemory=850 State=UNKNOWN

PartitionName=research Nodes=hpc-compute01 Default=YES MaxTime=INFINITE State=UP

SrunPortRange=60001-60010
