---
- name: Install Prometheus Node Exporter
  hosts: hpc_cluster
  become: true

  tasks:

    - name: Install node exporter
      apt:
        name: prometheus-node-exporter
        state: present
        update_cache: yes

    - name: Enable node exporter
      systemd:
        name: prometheus-node-exporter
        enabled: yes
        state: started
